### ISSUE TITLE
The alarm goes off when powered

### ISSUE THREAD

**Issue by nperozzi** [emanuelen5/kitchen-timer#22]
When you power the timer, the alarm goes off.

**Comment by emanuelen5** [comment]
This does not happen for me. I tried: 
1. Upload the "state_machine" sketch (revision 3bfb53817fe3359d4c499b4e5b061b1a1200c563)
2. Unplug and plug in the power again

**Comment by emanuelen5** [comment]
We haven't seen this problem in a while, so let's close it for now.
