### ISSUE TITLE
Queue overflow handling

### ISSUE THREAD

**Issue by nperozzi** [emanuelen5/kitchen-timer#25]
While implementing the rx_receive queue, I am facing the need to have queue overflow handling. At the moment we do not have it implemented on the queue library. Maybe we should?

**Comment by emanuelen5** [comment]
Yes, I think that's a good idea. Without it we won't be able to know if we lost data.

**Comment by emanuelen5** [comment]
A simple way would be to add it as a `bool` flag in the `dequeue_ret_t`, and clear it after it's read. We should add test cases for it before implementing :)
